routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/* Passando as rotas aqui.

Route::get('/categoria/{idCat}', function ($idCat) {
    return "Posts da categoria {$idCat}";

});

Route::get('/empresa', function () {
    return 'Pg empresa';

});

Route::get('/', function () {
    return view('welcome');
});*/



Route::get('/produto/testes','ProductController@testes');

Route::resource('/produto','ProductController');


Route::get('/contato','SiteController@contato'); 

Route::get('/','SiteController@index'); 

Route::get('/categoria/{id}','SiteController@categoria');

Route::get('/categoria2/{id?}','SiteController@categoria2');

resources/views/create-edit.blade.php
@extends('templates.template')


@section('content')

    <h1 class='title-pg'><a href="{{route('produto.index')}}"><span class='glyphicon glyphicon-fast-backward'></span> </a><b>Gestão Produto: {{$product->name  or 'Novo'}}</b></h1>

    <!--Mostrar quais campos ocorreram erros -->
    @if(isset($errors) && count($errors) > 0)
        <div class='alert alert-danger'>
            @foreach($errors->all() as $error)
                <p>{{$error}}</p>
            @endforeach
        </div>
    @endif
    <!---------------------------------------->


    <!--Se existe: É para editar-->    
    @if (isset($product))
            {!! Form::model($product,['route'=>['produto.update',$product->id],'class'=>'form','method'=>'put']) !!}
            
        @else
            {!! Form::open(['route'=>'produto.store','class'=>'form']) !!}
            
    @endif    
    
        <div class='form-group'>
            {!! Form::text('name',null,['class' =>'form-control','placeholder'=>'Nome:']) !!}
        </div>
        
        <div class='form-group'>
            <label>
                {!! Form::checkbox('active') !!}
                Ativo?
            </label>    
        </div>
            
        <div class='form-group'>
            {!! Form::text('number',null,['class' =>'form-control','placeholder'=>'Número:']) !!}            
        </div>
        
     
        @if (isset($product))

                <div class='form-group'>
        
                     {!! Form::select('category',$categorys,$num,['placeholder'=>'Escolha uma categoria','class'=>'form-control']) !!}   
                </div>
                
            @else
                
            <div class='form-group'>
                 {!! Form::select('category',$categorys,null,['placeholder'=>'Escolha uma categoria','class'=>'form-control']) !!}   
            </div>
    @endif   

        
        <div class='form-group'>
            {!! Form::textarea('description',null,['class' =>'form-control','placeholder'=>'Descrição:']) !!}
        </div>
        
        {!! Form::submit('Enviar',['class'=>'btn btn-primary']) !!}
    
    {!! Form::close() !!}
    
@endsection

resources/views/products.blade.php
@extends('templates.template')

@section('content')

    <H1 class="title-pg">Listagem dos produtos</H1>
    
    <!--<a href="{{url('produto/create')}}" class="btn btn-primary btn-add"><span class="glyphicon glyphicon-plus"></span> Cadastrar</a>-->
    <a href="{{route('produto.create')}}" class="btn btn-primary btn-add"><span class="glyphicon glyphicon-plus"></span> Cadastrar</a>
    
    
    <table class="table table-striped" >
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th widtb='300px'>Ações</th>
        </tr>
            
        @foreach($products as $produto)
            <tr>
                <td>{{$produto->name}}</td>
                <td>{{$produto->description}}</td>
                <td>
                    <a href="{{route('produto.edit',$produto->id)}}" class="edit actions"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a href="{{route('produto.show',$produto->id)}}" class="delete actions"><span class="glyphicon glyphicon-eye-open"></span></a>
                </td>
            </tr>
        @endforeach
        
    </table>
    
    
    {!! $products->links() !!}

@endsection

resources/views/show.blade.php
@extends('templates.template')

@section('content')

<H1 class="title-pg">    <h1 class='title-pg'><a href="{{route('produto.index')}}"><span class='glyphicon glyphicon-fast-backward'></span> </a>Produto : <b>{{$product->name}}</b></H1>
    
   <p><b>Ativo:</b>{{$product->active}}</p> 
   <p><b>Número:</b>{{$product->number}}</p>     
   <p><b>Categoria:</b>{{$product->category}}</p> 
   <p><b>Descrição:</b>{{$product->description}}</p> 
   
   <hr>
   <!--Caso ocorra algum erro -->
    @if(isset($errors) && count($errors) > 0)
        <div class='alert alert-danger'>
            @foreach($errors->all() as $error)
                <p>{{$error}}</p>
            @endforeach
        </div>
    @endif   
   
   
   {!! Form::open(['route'=>['produto.destroy',$product->id], 'method'=>'DELETE']) !!}
   
    {!! Form::submit("Deletar Produto $product->name",['class'=>'btn btn-danger']) !!}
   
   {!! Form::close() !!}
       
@endsection